name: Deploy to Surge

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Cambiado a 20 para compatibilidad con Astro

      - name: Instalar dependencias
        run: npm install

      - name: Generar build
        run: npm run build  # Asegúrate de que tu build genere la carpeta dist

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar en Surge
        run: surge ./dist unsuitable-distance.surge.sh --token ${{ secrets.SURGE_TOKEN }}
