name: Deploy to Surge

on:
    push:
        branches:
            - main  # Se ejecuta cuando hagas push en la rama main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
            
            - name: Instalar Surge
              run: npm install -g surge

            - name: Deploy
              run: surge ./dist unsuitable-distance.surge.sh --token ${{ secrets.SURGE_TOKEN }}
