name: Deploy Astro to surge

on:
  push:
    branches:
      - feauture/home

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Generar el sitio estático
        run: npm run build
      
      - name: instalar surge
        run: npm install -g surge
      
      - name: Desplegar en Surge
        run: surge ./dist unsuitable-distance.surge.sh --token ${{ secrets.SURGE_TOKEN }}
